// Test generated by RoostGPT for test testArtillery using AI Type Open AI and AI Model gpt-4


// Test generated for /user/{username}_get for http method type GET in rest-assured framework


// RoostTestHash=da281fe471


package org.agoncal.application.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;

public class user_usernameGetTest {
  
    @Test  
    public void user_username_get_Test() {  
        RestAssured.baseURI = System.getenv("BASE_URL");  
  
        // Read CSV file  
        try (BufferedReader reader = new BufferedReader(new FileReader("src/test/java/org/agoncal/application/RoostTest/user_username_get.csv"))) {  
            String headerLine = reader.readLine();  
            String[] headers = headerLine.split(",");  
  
            String line;  
            while ((line = reader.readLine()) != null) {  
                String[] data = line.split(",");  
  
                // Create a map of header to data  
                Map<String, String> map = new HashMap<>();  
                for (int i = 0; i < headers.length; i++) {  
                    map.put(headers[i], data[i]);  
                }  
                
  
                Response response = given()
				.pathParam("username", map.get("username"))
                .when()
                .get("/user/{username}")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 200) {
					System.out.println("Description: successful operation");
  
            if (response.jsonPath().get("id") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("id"), instanceOf(Integer.class));
                MatcherAssert.assertThat(response.jsonPath().getString("id"), Number.isSafeInteger(
                  response.jsonPath().getInt("id")
                )); 
  
          }
  
            if (response.jsonPath().get("username") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("username"), instanceOf(String.class));  
          }
  
            if (response.jsonPath().get("firstName") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("firstName"), instanceOf(String.class));  
          }
  
            if (response.jsonPath().get("lastName") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("lastName"), instanceOf(String.class));  
          }
  
            if (response.jsonPath().get("email") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("email"), instanceOf(String.class));  
          }
  
            if (response.jsonPath().get("password") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("password"), instanceOf(String.class));  
          }
  
            if (response.jsonPath().get("phone") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("phone"), instanceOf(String.class));  
          }
  
            if (response.jsonPath().get("userStatus") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("userStatus"), instanceOf(Integer.class));  
          }
				}
if (response.statusCode() == 400) {
					System.out.println("Description: Invalid username supplied");
				}
if (response.statusCode() == 404) {
					System.out.println("Description: User not found");
				}
  
            }  
        } catch (IOException e) {  
            e.printStackTrace();  
        }  
    }
}
