// Test generated by RoostGPT for test testArtillery using AI Type Open AI and AI Model gpt-4


// Test generated for /user/{username}_put for http method type PUT in rest-assured framework


// RoostTestHash=f6e646c39e


package org.agoncal.application.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;

public class user_usernamePutTest {
  
    @Test  
    public void user_username_put_Test() {  
        RestAssured.baseURI = System.getenv("BASE_URL");  
  
        // Read CSV file  
        try (BufferedReader reader = new BufferedReader(new FileReader("src/test/java/org/agoncal/application/RoostTest/user_username_put.csv"))) {  
            String headerLine = reader.readLine();  
            String[] headers = headerLine.split(",");  
  
            String line;  
            while ((line = reader.readLine()) != null) {  
                String[] data = line.split(",");  
  
                // Create a map of header to data  
                Map<String, String> map = new HashMap<>();  
                for (int i = 0; i < headers.length; i++) {  
                    map.put(headers[i], data[i]);  
                }  
                
  
                Response response = given()
				.pathParam("username", map.get("username"))
				.pathParam("body", map.get("body"))
                .when()
                .put("/user/{username}")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 400) {
					System.out.println("Description: Invalid user supplied");
				}
if (response.statusCode() == 404) {
					System.out.println("Description: User not found");
				}
  
            }  
        } catch (IOException e) {  
            e.printStackTrace();  
        }  
    }
}
